### ISSUE TITLE
Easy way to post a number of alerts inside the same headline and be able to comment on the posts

### ISSUE THREAD

**Issue by MOKknudsen** [EvotecIT/PSTeams#16]
How would I define a headline like "MFA errors"
Under the headline, I would like to post a section per user with details about their particular issue
and I want to be able to reply on each section like 'user problem was fixed by Morten'

**Comment by PrzemyslawKlys** [comment]
Have you done any research on the subject using PSTeams?

**Comment by MOKknudsen** [comment]
I have solved it as a workaround – case closed 😊

Med venlig hilsen | Best Regards​
Morten Waltorp Knudsen
CEO & Senior Consultant
[cid:image011.jpg@01D6129D.2FFB1D80]<https://2linkit.net/wp-content/uploads/2018/02/53A1809.jpg>
[cid:image012.png@01D6129D.2FFB1D80]
+45 40 178 179<tel:+45%2040%20178%20179>
[cid:image013.png@01D6129D.2FFB1D80]
MOK@2LINKIT.NET<mailto:MOK@2linkit.net>
[cid:image014.png@01D6129D.2FFB1D80]
[cid:image015.png@01D6129D.2FFB1D80]
[cid:image016.png@01D6129D.2FFB1D80]
[cid:image017.png@01D6129D.2FFB1D80]
[cid:image018.png@01D6129D.2FFB1D80]
[cid:image019.png@01D6129D.2FFB1D80]<http://www.2linkit.net/>
Strandvejen 21A
6000
Kolding
Denmark
2linkIT QuickSupport ​(TeamViewer)
​<https://get.teamviewer.com/2linkit-support>https://get.teamviewer.com/2linkit-support
