### ISSUE TITLE
How can I make a post with a mention, so IT dept gets notifications about the post

### ISSUE THREAD

**Issue by MOKknudsen** [EvotecIT/PSTeams#17]
How can I make a post with a mention, so IT dept gets notifications about the post

https://myteamsday.com/2019/03/05/sending-message-with-atmention-onto-a-channel-using-graphapi/

**Comment by PrzemyslawKlys** [comment]
Right now PSTeams supports only Message Cards using Incoming Webhook and not Graph API. It doesn't support Mentions. However, this is an interesting subject for me. Maybe I should pursue this. 

In the meantime, you could try using: https://www.powershellgallery.com/packages/Microsoft.Graph.Teams.Chats straight from Microsoft :-)

**Comment by MOKknudsen** [comment]
I would really appreciate if you could look into this. I’m really happy with your work in PSTeams 😊

Med venlig hilsen | Best Regards​
Morten Waltorp Knudsen
CEO & Senior Consultant
[cid:image011.jpg@01D6129D.005B57C0]<https://2linkit.net/wp-content/uploads/2018/02/53A1809.jpg>
[cid:image012.png@01D6129D.005B57C0]
+45 40 178 179<tel:+45%2040%20178%20179>
[cid:image013.png@01D6129D.005B57C0]
MOK@2LINKIT.NET<mailto:MOK@2linkit.net>
[cid:image014.png@01D6129D.005B57C0]
[cid:image015.png@01D6129D.005B57C0]
[cid:image016.png@01D6129D.005B57C0]
[cid:image017.png@01D6129D.005B57C0]
[cid:image018.png@01D6129D.005B57C0]
[cid:image019.png@01D6129D.005B57C0]<http://www.2linkit.net/>
Strandvejen 21A
6000
Kolding
Denmark
2linkIT QuickSupport ​(TeamViewer)
​<https://get.teamviewer.com/2linkit-support>https://get.teamviewer.com/2linkit-support

**Comment by MOKknudsen** [comment]
How can I attach file to the post in teams?


Med venlig hilsen | Best Regards
Morten Waltorp Knudsen
CEO & Senior Consultant
+45 40 178 179
MOK@2LINKIT.NET
Strandvejen 21A
6000Kolding
Denmark
2linkIT QuickSupport ​(TeamViewer)
​https://get.teamviewer.com/2linkit-support
________________________________
Fra: Przemysław Kłys <notifications@github.com>
Sendt: Tuesday, April 14, 2020 8:34:41 PM
Til: EvotecIT/PSTeams <PSTeams@noreply.github.com>
Cc: Morten Waltorp Knudsen <MOK@2LINKIT.NET>; Author <author@noreply.github.com>
Emne: [EXT] Re: [EvotecIT/PSTeams] How can I make a post with a mention, so IT dept gets notifications about the post (#17)


Right now PSTeams supports only Message Cards using Incoming Webhook and not Graph API. It doesn't support Mentions. However, this is an interesting subject for me. Maybe I should pursue this.

In the meantime, you could try using: https://www.powershellgallery.com/packages/Microsoft.Graph.Teams.Chats<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.powershellgallery.com%2Fpackages%2FMicrosoft.Graph.Teams.Chats&data=02%7C01%7Cmok%402linkit.net%7C1821a2dbc8a242af3bdb08d7e0a27f98%7Cf0fa27a08e7c4f639a77ec94786b7c9e%7C1%7C0%7C637224860851060873&sdata=b26inEKNJg1SeqWgN9SmoO17kcP5qmhvLECijiZx2wQ%3D&reserved=0> straight from Microsoft :-)

**Comment by PrzemyslawKlys** [comment]
It's not supported in Message Cards, It may be supported by Graph API

**Comment by MOKknudsen** [comment]
It appears so:

You can post messages with card attachments referencing existing SharePoint files using the Microsoft Graph APIs for OneDrive and SharePoint<https://docs.microsoft.com/en-us/onedrive/developer/rest-api/>. Using the Graph APIs requires obtaining access to a user's OneDrive folder (for personaland groupchat files) or the files in a team's channels (for channel files) through the standard OAuth 2.0 authorization flow.

Please have a look at Send and receive files<https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-files#using-the-microsoft-graph-apis>documentation.



Med venlig hilsen | Best Regards
Morten Waltorp Knudsen
CEO & Senior Consultant
+45 40 178 179
MOK@2LINKIT.NET
Strandvejen 21A
6000Kolding
Denmark
2linkIT QuickSupport ​(TeamViewer)
​https://get.teamviewer.com/2linkit-support
________________________________
Fra: Przemysław Kłys <notifications@github.com>
Sendt: Tuesday, April 14, 2020 10:52:50 PM
Til: EvotecIT/PSTeams <PSTeams@noreply.github.com>
Cc: Morten Waltorp Knudsen <MOK@2LINKIT.NET>; Author <author@noreply.github.com>
Emne: [EXT] Re: [EvotecIT/PSTeams] How can I make a post with a mention, so IT dept gets notifications about the post (#17)


It's not supported in Message Cards, It may be supported by Graph API

**Comment by MOKknudsen** [comment]
Hi again,
Do you have any experience in integrating Flow/Power apps workflow with an approval proces.
Example:

  *   I run some PS script which posts something to Teams channel
  *   Flow picks up the post and starts a workflow with approval (yes/no).
  *   The reply should go back to the thread in Teams as APPROVED or DENIED
  *   Then another PS script should do a Get-TeamsMessage or similar that detects the response

Med venlig hilsen | Best Regards​
Morten Waltorp Knudsen
CEO & Senior Consultant
[cid:image011.jpg@01D61408.0BE047B0]<https://2linkit.net/wp-content/uploads/2018/02/53A1809.jpg>
[cid:image012.png@01D61408.0BE047B0]
+45 40 178 179<tel:+45%2040%20178%20179>
[cid:image013.png@01D61408.0BE047B0]
MOK@2LINKIT.NET<mailto:MOK@2linkit.net>
[cid:image014.png@01D61408.0BE047B0]
[cid:image015.png@01D61408.0BE047B0]
[cid:image016.png@01D61408.0BE047B0]
[cid:image017.png@01D61408.0BE047B0]
[cid:image018.png@01D61408.0BE047B0]
[cid:image019.png@01D61408.0BE047B0]<http://www.2linkit.net/>
Strandvejen 21A
6000
Kolding
Denmark
2linkIT QuickSupport ​(TeamViewer)
​<https://get.teamviewer.com/2linkit-support>https://get.teamviewer.com/2linkit-support

**Comment by PrzemyslawKlys** [comment]
PSTeams is not going to help you with that, at least not in the near future.

**Comment by MOKknudsen** [comment]
is it possible to get a URL link to the message, I post to Teams, so I can refer to it e.g. in a planner task just below my post

Med venlig hilsen | Best Regards​
Morten Waltorp Knudsen
CEO & Senior Consultant
[cid:image011.jpg@01D619C2.C0EA51E0]<https://2linkit.net/wp-content/uploads/2018/02/53A1809.jpg>
[cid:image012.png@01D619C2.C0EA51E0]
+45 40 178 179<tel:+45%2040%20178%20179>
[cid:image013.png@01D619C2.C0EA51E0]
MOK@2LINKIT.NET<mailto:MOK@2linkit.net>
[cid:image014.png@01D619C2.C0EA51E0]
[cid:image015.png@01D619C2.C0EA51E0]
[cid:image016.png@01D619C2.C0EA51E0]
[cid:image017.png@01D619C2.C0EA51E0]
[cid:image018.png@01D619C2.C0EA51E0]
[cid:image019.png@01D619C2.C0EA51E0]<http://www.2linkit.net/>
Strandvejen 21A
6000
Kolding
Denmark
2linkIT QuickSupport ​(TeamViewer)
​<https://get.teamviewer.com/2linkit-support>https://get.teamviewer.com/2linkit-support

**Comment by PrzemyslawKlys** [comment]
Don't think so.

**Comment by anhducng** [comment]
It looks like MS Teams now support mention within Adaptive Card

https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#mention-support-within-adaptive-cards

**Comment by PrzemyslawKlys** [comment]
I'll verify this, but:

![image](https://user-images.githubusercontent.com/15063294/138233705-28a93e8c-8316-40a5-83dc-c8afb6b3e345.png)

So it says bots and messaging extensions - what we do may not be applicable. And i you check my tries from months back I was using the code they propose

https://github.com/EvotecIT/PSTeams/blob/1198dd77be84bf6bbef9dda7396a55a32cdd9df5/Public/New-AdaptiveCard.ps1#L171-L207

But maybe they enabled it in the backend and we just need to check things.

**Comment by robinmalik** [comment]
This works: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#user-mention-in-incoming-webhook-with-adaptive-cards

but the user doesn't receive any notification they've been tagged. Note:

![image](https://user-images.githubusercontent.com/8790561/143611978-1bfe1f62-be46-4678-8d4e-b4cc99783c86.png)

**Comment by PrzemyslawKlys** [comment]
ok, super cool. Time to add it I guess :)

**Comment by PrzemyslawKlys** [comment]
Well, it seems not much have changed

![image](https://user-images.githubusercontent.com/15063294/144704566-5110e7c6-a795-4fc0-ad19-dbca25e8700b.png)

It still acts the same 1 year later

![image](https://user-images.githubusercontent.com/15063294/144704576-80724030-d0cc-4413-92e6-e9c8ecc35cf3.png)

I guess I can add it, and when it's really usable it will just start working.

**Comment by PrzemyslawKlys** [comment]
Mentions added:

![image](https://user-images.githubusercontent.com/15063294/144713208-771f10e5-f5bb-4556-ba4b-fde5b13c8b0d.png)

```powershell
New-AdaptiveCard -Uri $Env:TEAMSPESTERID -VerticalContentAlignment center {
    New-AdaptiveTextBlock -Size ExtraLarge -Weight Bolder -Text 'Test' -Color Attention -HorizontalAlignment Center
    New-AdaptiveColumnSet {
        New-AdaptiveColumn {
            New-AdaptiveTextBlock -Size 'Medium' -Text 'Test Card Title 1' -Color Dark
            New-AdaptiveTextBlock -Size 'Medium' -Text 'Test Card Title 1' -Color Light
        }
        New-AdaptiveColumn {
            New-AdaptiveTextBlock -Size 'Medium' -Text 'Test Card Title 1' -Color Warning
            New-AdaptiveTextBlock -Size 'Medium' -Text 'Test Card Title 1' -Color Good
        }
        New-AdaptiveColumn {
            New-AdaptiveTextBlock -Size 'Medium' -Text 'Test Card Title 1 <at>Name</at>' -Color Warning
            New-AdaptiveTextBlock -Size 'Medium' -Text 'Test Card Title 1 <at>Zenon Jaskuła</at>' -Color Warning
        }
    }
    New-AdaptiveMention -Text 'Zenon Jaskuła' -UserPrincipalName 'przemyslaw.klys@evotec.test'
    New-AdaptiveMention -Text 'Name' -UserPrincipalName 'przemyslaw.klys@evotec.test'
} -Verbose #-SelectAction Action.OpenUrl -SelectActionUrl 'https://evotec.xyz'
```

But it's a bit useless because mention is mention, but without notification ;/

**Comment by PrzemyslawKlys** [comment]
Closing, hopefully things will start working automatically once Microsoft enables it.

**Comment by robinmalik** [comment]
Mention notifications now work and have tested the above code - all good.

**Comment by PrzemyslawKlys** [comment]
Great! I just tested and it seems to work, with just one issue - you need <at> chars are removed along with the data so you need to add additional text... or are you seeing something different?

```
        New-AdaptiveColumn {
            New-AdaptiveTextBlock -Size 'Medium' -Text 'Test Card Title 1 <at>Name</at>' -Color Warning
            New-AdaptiveTextBlock -Size 'Medium' -Text 'Test Card Title 1 <at>Przemysław Kłys</at> Przemysław Kłys' -Color Warning
        }
```

![image](https://user-images.githubusercontent.com/15063294/149210377-5821d191-4b6b-441e-9c08-fd62066a263d.png)

**Comment by PrzemyslawKlys** [comment]
It seems the implementation should be: `"text": "Hi <at>Adele UPN</at>, <at>Adele AAD</at>"` so it would seem you need to do both?

Source: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#user-mention-in-incoming-webhook-with-adaptive-cards

**Comment by robinmalik** [comment]
I'm not sure exactly what you mean by "you need chars are removed along with the data so you need to add additional text" but I think I know what you mean. This worked for me, outputting "Hello Robin" only (but I get the notification, and that's the tag text):

```
New-AdaptiveCard -Uri $TeamsID -FullWidth -VerticalContentAlignment center {
    New-AdaptiveTextBlock -Size ExtraLarge -Weight Bolder -Text 'Test' -Color Attention -HorizontalAlignment Center
    New-AdaptiveColumnSet {
        New-AdaptiveColumn {
            New-AdaptiveTextBlock -Size 'Medium' -Text 'Test Card Title 1'
        }
        New-AdaptiveColumn {
            New-AdaptiveTextBlock -Size 'Medium' -Text 'Hello Robin <at>Robin Malik</at>'
        }
    }
    New-AdaptiveMention -Text 'Robin Malik' -UserPrincipalName 'username@domain.com'
}
```
I think the documentation is just being a little lazy, using a single TextBlock to generate/link to two methods of tagging/notifying users.

**Comment by PrzemyslawKlys** [comment]
Right, so you need to add text you want to display and at the same time at <at> to get notified, but then you loose the "marking" that you normally get, which I guess is ok, but somewhat inconsistent.

**Comment by robinmalik** [comment]
@PrzemyslawKlys Right yes, it's trimming the text at the end that's enclosed in `<at></at>`. This isn't my experience with code I currently use for AdaptiveCards which retains it.
