### ISSUE TITLE
New-TeamsActivityImage missing images

### ISSUE THREAD

**Issue by wahidsaleemi** [EvotecIT/PSTeams#19]
New-TeamsActivityImage missing images:
ValidateSet does not include Question, Reload, or Info images. It does have Download, but no corresponding file (download.jpg).

**Comment by PrzemyslawKlys** [comment]
You're right. I probably need to find free images that are small enough and that match our needs. I don't know how it happened.

**Comment by PrzemyslawKlys** [comment]
Published fixed version.
