### ISSUE TITLE
The parameter “ActivityImage” of the “New-TeamsSection” command does not work

### ISSUE THREAD

**Issue by lingyf** [EvotecIT/PSTeams#22]
Hello there,

I am using the latest version of the "PSTeams" module and found that the parameter "ActivityImage" of the "New-TeamsSection" command does not work. I checked the source code and found that the "StoredImages" path may not correct, here is a possible solution:

PSTeams.psm1 Line 651-654
```diff
if ($ActivityImage -ne 'None') {
-    $StoredImages = [IO.Path]::Combine("$(Split-Path -Path $PSScriptRoot -Parent)", "Images")
+    $StoredImages = [IO.Path]::Combine($PSScriptRoot, "Images")
     $ActivityImageLink = Get-Image -PathToImages $StoredImages -FileName $ActivityImage -FileExtension '.jpg' # -Verbose
}
```

Best Regards,
Albert

**Comment by PrzemyslawKlys** [comment]
Nah, it's not related to path. I believe it's related to name of the property. It should be ActivityImage

https://github.com/EvotecIT/PSTeams/blob/b09a53aa619a60993bed0718c546ef2606fa22c2/Public/New-TeamsActivityImage.ps1#L12-L13

**Comment by PrzemyslawKlys** [comment]
Or maybe not. Investigating.

**Comment by PrzemyslawKlys** [comment]
Changed it to: `$StoredImages = [IO.Path]::Combine($PSScriptRoot, '..', 'Images')` which is proper way I believe, as the ScriptRoot where the path is checked is. This is the path that is correct for "non" merged resources (before publishing). Now i need to add code to my publishing module to replace it on the fly with proper path.

**Comment by PrzemyslawKlys** [comment]
Published new version
