### ISSUE TITLE
What format should the $TeamsID be in? Invoke-RestMethod:  is failing

### ISSUE THREAD

**Issue by JeromeLC** [EvotecIT/PSTeams#3]
`Invoke-RestMethod : The resource you are looking for has been removed, had its name changed, or is temporarily
unavailable.
At C:\Program Files\WindowsPowerShell\Modules\PSTeams\0.2.3\PSTeams.psm1:488 char:16`

**Comment by PrzemyslawKlys** [comment]
It should be URL string for webhook. Have you followed steps: https://evotec.xyz/hub/scripts/psteams-powershell-module/ to create webhook? Use that URL as TeamsID.

**Comment by JeromeLC** [comment]
That worked. Thank you very much for the speedy reply.
