### ISSUE TITLE
Support for uploading a file to a Teams message

### ISSUE THREAD

**Issue by TechDufus** [EvotecIT/PSTeams#32]
Is it possible to add a parameter `-Attachment` and point to a local file path to attach a file to the message?

**Comment by PrzemyslawKlys** [comment]
Don't think incoming webhooks support sending files. That would be great - if you find out that it supports this we can work it out.

**Comment by TechDufus** [comment]
Dadgummit.. I should have done a search before making this issue. It looks like it's not supported yet.

https://stackoverflow.com/questions/53982764/send-files-to-microsoft-teams-using-webhook#53984068

**Comment by PrzemyslawKlys** [comment]
I've found it too. But that's a very old thread and according to that Adaptive Cards are not supported either - yet here we are using Adaptive Cards in incoming webhook.

**Comment by PrzemyslawKlys** [comment]
Closing in favor of #36
