### ISSUE TITLE
Is it possible to detect messages received also?

### ISSUE THREAD

**Issue by numericOverflow** [EvotecIT/PSTeams#33]
This is very cool, but can it also be used to trigger when chats/messages are received by the user?  If not, is there another way to do so?

I haven't found a way to programmatically trigger actions on my local machine when someone messages me. For example, flash the screen, or add an entry to a log file, etc.

Thanks!

**Comment by PrzemyslawKlys** [comment]
PSTeams isn't capable of doing that. You would need to dive deep into Graph and most likely do some serious coding.
