### ISSUE TITLE
support of Full width Adaptive card

### ISSUE THREAD

**Issue by tomabg** [EvotecIT/PSTeams#35]
Hi,

according to the documentation in https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html

There is a possibility to enlarge adaptive cards by using:
    "msteams": {
        "width": "Full"
    }

Is there a possibility to use that with this nice module?

BR
Thomas

**Comment by PrzemyslawKlys** [comment]
Great find! Thank you. Added it and made default. I was not able to find this setting before and it was driving me crazy.

**Comment by PrzemyslawKlys** [comment]
Although I am now thinking if it should be default

![image](https://user-images.githubusercontent.com/15063294/115536286-eb852680-a299-11eb-99ea-c2c5665152ae.png)

Maybe on demand, and default as current size?

**Comment by tomabg** [comment]
yeah on demand is better option because this change would maybe destroy existing running installations/card design by update

Thank you for prompt response

**Comment by PrzemyslawKlys** [comment]
Added -FullWidth switch. Thank you again for this doc.

**Comment by tomabg** [comment]
looks very nice...seems example in doc needs an update too to use -FullWidth  instead of -with full

if you interested i can send you my cards via mail or other channels

**Comment by tomabg** [comment]
Many Thanks for this enhancement

**Comment by PrzemyslawKlys** [comment]
Should be ok now :) Sure - I like to see what people do with my modules.
