### ISSUE TITLE
Question: Is it possible to create a teams approval through this module?

### ISSUE THREAD

**Issue by richard-tonyson-cab** [EvotecIT/PSTeams#37]
Hi
My question is as the title suggest. I am very pleased with the PSTeams module, nice examples. However, I wonder if the module can create approvals as well? If not, do you know how that would be done?
Best regards, 
Richard

**Comment by PrzemyslawKlys** [comment]
You can't, as it requires server-side. Most likely PowerAutomate would be a better choice, eventually Teams Bot, but I guess PowerAutomate should do the trick.

There's also an application called Approvals - https://docs.microsoft.com/en-us/power-automate/teams/native-approvals-in-teams

**Comment by richard-tonyson-cab** [comment]
Ok, thanks for the superquick response!
