### ISSUE TITLE
SSL Connection could not be Established

### ISSUE THREAD

**Issue by ayush-lal** [EvotecIT/PSTeams#38]
I get the following error when using Send-TeamsMessage. Any idea on how I could bypass the SSL validation? 

```
WARNING: Send-TeamsMessage - Couldn't send message. Error: The SSL connection could not be established, see inner exception.
```

**Comment by PrzemyslawKlys** [comment]
If an SSL connection is not established it's most likely because the firewall blocks it or your "devices" somehow block it. Don't think there's anything you can do about it.
