### ISSUE TITLE
Creating a Table

### ISSUE THREAD

**Issue by ayush-lal** [EvotecIT/PSTeams#39]
Is there a way to create a table in a card?

**Comment by PrzemyslawKlys** [comment]
As far as I know only a "sort-of" table. 

- https://techcommunity.microsoft.com/t5/microsoft-365-pnp-blog/how-to-create-a-faux-table-in-adaptive-cards-with-power-automate/ba-p/2188288

![image](https://user-images.githubusercontent.com/15063294/121306380-0de10b00-c8ff-11eb-9c37-ba9e1d370117.png)

- https://adaptivecards.io/samples/ExpenseReportWithLabels.html

![image](https://user-images.githubusercontent.com/15063294/121306326-fbff6800-c8fe-11eb-9e85-c5a740f59338.png)

We could probably add a New-AdaptiveCardTable function that would minimize the effort required to create a table by hand using New-AdaptiveColumnSet, New-AdaptiveColumn. It could be useful to a lot of people.

**Comment by PrzemyslawKlys** [comment]
This was added a while back: https://evotec.xyz/adaptive-cards-with-tables-and-linebreaks-in-microsoft-teams/
