### ISSUE TITLE
Problems with the module

### ISSUE THREAD

**Issue by GoebloJr** [EvotecIT/PSTeams#41]
The last Days everything was working fine but now if i try to run the script it throws the error that the command -MessageTitle is not found and that the remotserver returns with error 400 and i´ve triple checked if my url is correct. 
Maybe someone has a solution.
![Unbenannt](https://user-images.githubusercontent.com/86778156/125776801-ebfb18d6-4c70-41ab-a742-3c0b80a9c3fd.PNG)

**Comment by PrzemyslawKlys** [comment]
Well maybe message title is not set? You're not giving enough information to help you. The error message is pretty clear. Maybe you have another module in conflict.

**Comment by GoebloJr** [comment]
![Unbenannt](https://user-images.githubusercontent.com/86778156/125803988-1e889ba0-0520-44de-8b35-97ea5a15e9b3.PNG)
Thats all i wrote  in the script. it should only send little message for missed caller. 
I´m kinda new to the world of programming and scripting so be kind :D

**Comment by PrzemyslawKlys** [comment]
If I had to guess your problem is backtick next to -URI $teamsID`. Add a space between variable and backtick and problems will go away.
