### ISSUE TITLE
Module to be totally portable and no installation on Windows itself?

### ISSUE THREAD

**Issue by GoebloJr** [EvotecIT/PSTeams#42]
Hello,
is it possible to use your Module without installation on windows so it can run on every Computer in combination with an exe file which calls the script to start everything?

**Comment by PrzemyslawKlys** [comment]
Use `Save-Module` to get the version from PSGallery and save it anywhere you want. After that `Import-Module` call PSD1 directly. Anyways Install-module - what it does is just puts the folder in one of the `$Env:PSModulePath` paths - and that's it. There's nothing special about modules installation.

**Comment by GoebloJr** [comment]
I will try thank you !
