### ISSUE TITLE
unable to @mention

### ISSUE THREAD

**Issue by dlehr4** [EvotecIT/PSTeams#43]
This is a critical functionality piece for triggering chat bots or just notifying specific tagged members in a MS teams channel. Is there any plan to implement this functionality?

https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=powershell#example-8---a-team-in-a-channel-message

**Comment by PrzemyslawKlys** [comment]
It's already added - https://evotec.xyz/mentioning-users-in-notifications-using-psteams-powershell-module/

Keep in mind we don't use Graph API.
