### ISSUE TITLE
Enable use of proxy when sending Teams messages

### ISSUE THREAD

**Issue by theramiyer** [EvotecIT/PSTeams#44]
Some environments sit behind a proxy. Can we enable specifying the proxy with `Send-TeamsMessage`?

**Comment by theramiyer** [comment]
If this feature is okay to implement, I would like to contribute ([here is the commit](https://github.com/theramiyer/PSTeams/commit/5b3fcb25d98d75413789522b010e8a86011835b7)). However, I'm unable to figure out how to write a Pester test for use with the proxy. Would like some help there.

Thanks in advance! :)

**Comment by PrzemyslawKlys** [comment]
Hi, seems nice, but probably should be `[URI]` instead of [string] as Invoke-RestMethod takes that as an argument. Feel free to create PR

**Comment by theramiyer** [comment]
Thank you! I'll modify that. Also, I'm wondering how to write a Pester test for this; can we use a public proxy? Or can we skip the test for this parameter?

**Comment by PrzemyslawKlys** [comment]
I am not sure I trust public proxy unless it's some company like Mozilla or Cloduflare. So pester test only if that proxy is kind of trusted.

**Comment by theramiyer** [comment]
I don't know of a trusted proxy. Given that the information is passed as-is, can we skip the test for this parameter?

**Comment by theramiyer** [comment]
Created pull request #45 for this.

**Comment by theramiyer** [comment]
Can we close this issue? I'm unaware of the convention here. :)

**Comment by PrzemyslawKlys** [comment]
Yup, i'll release new version soon
