### ISSUE TITLE
Error 405

### ISSUE THREAD

**Issue by mvit777** [EvotecIT/PSTeams#47]
Hi,
thanx for releasing this module. However I have an issue.
I set up a channel on my "personal" teams client.
then with this code I got a 405 error. Seems I'm not allowd to post the channel but I did not set any authentication.
What am I missing?

```powershell
Import-Module -Name '..\common.ranx.org\common-import.psm1'
$teamid = "https://teams.microsoft.com/l/channel/19%3aBLEVr8ZdN6hozld9B0TWkJkix3s7AcOzQIFvNGmv5CU1%40thread.tacv2/General?groupId=a14a3b75-72e5-4ed4-9663-b06f09066921&tenantId=e6de4fa2-b6b0-4830-bc05-d7f9b0d226c6"

New-ThumbnailCard -Title 'Bender' -SubTitle "tale of a robot who dared to love" -Text "Bender Bending Rodríguez is a main character in the animated television series Futurama. He was created by series creators Matt Groening and David X. Cohen, and is voiced by John DiMaggio" {
    New-ThumbnailImage -Url 'https://upload.wikimedia.org/wikipedia/en/a/a6/Bender_Rodriguez.png' -AltText "Bender Rodríguez"
} -Uri $teamid
```
Error message

**WARNING: Send-TeamsMessageBody - Couldn't send message. Error: Response status code does not indicate success: 405 (Method Not Allowed).**

it seems I'm not sending the correct headers either

**Comment by PrzemyslawKlys** [comment]
It's not about TeamID. You need to add a connector:
- https://evotec.xyz/hub/scripts/psteams-powershell-module/ - scroll to the "How to set it up?"

**Comment by mvit777** [comment]
Do you suggest OFFICE365 connector?
thanks so much.
