### ISSUE TITLE
Any chance to decouple the PSSharedGoods module?

### ISSUE THREAD

**Issue by bodybybuddha** [EvotecIT/PSTeams#5]
Big ask - anyway of getting a version of PSTeams without the PSSharedGoods module requirement?  I understand the purpose, but the PSSharedGoods has a lot of functionality that just isn't used in PSTeams and it exposes a lot of commands that I already had duplicate functions.

Thanks!
JT

**Comment by PrzemyslawKlys** [comment]
Hi,

I guess I could do that. Currently, functions are duplicated but there are few functions I wanted to remove from PSTeams and keep only in PSSharedGoods. Those functions are duplicated among 3 or 4 modules now and thought PSSharedGoods (which is built for exactly this purpose) would take that over. But if you think it's not a good idea I'll republish.

Przemek

**Comment by bodybybuddha** [comment]
That would be amazing if you could.  I completely understand the duplication of code.  However, I think it would make the module much 'cleaner' -- and it more focused on just one task.  

While very useful, modules like PSSharedGoods, are very generic and I think any PowerShell scripter / team has a generic module very much like it.  However, their works in their setup/environment, etc.  To me, modules should be pretty self contained with any helper functions built into the module.  Not to say that module dependencies shouldn't exist - but if they do, they should be for other very focused modules.

In any event, I can guarantee you that the modified version without the dependency will get a TON of usage from me and my team.

**Comment by PrzemyslawKlys** [comment]
I understand. I will remove it for now and when I'll get time I'll update my PSPublishModule module to not only merge functions from the current module but also merge any functions that are required from other modules. It may take time to build that, so, for now, I'll have some duplicate code. Alternatively, I will think about splitting PSSharedGoods into smaller, more focused modules. But I would prefer the 1st option.

**Comment by PrzemyslawKlys** [comment]
Update-Module PSTeams 

It's removed.

**Comment by bodybybuddha** [comment]
Awesome!  Updating and socializing with my team now!
