### ISSUE TITLE
New-AdaptiveTable Doesn't permit variable-width columns

### ISSUE THREAD

**Issue by ObsidianPhoenix** [EvotecIT/PSTeams#51]
When using the `New-AdaptiveTable` function, passing in data results in all columns with identical widths.

![image](https://github.com/EvotecIT/PSTeams/assets/5765633/6d19930a-e038-432d-8eed-aa7ee02b14c2)

On investigation, it appears to be due to setting the width to stretch on the columns:

https://github.com/EvotecIT/PSTeams/blob/f532431ef931f50cd94bd9f1768c390e945d01bc/Public/New-AdaptiveTable.ps1#L225

This is from the [Renderer Guide](https://learn.microsoft.com/en-us/adaptive-cards/rendering-cards/renderer-behaviour) on MS:

> Columns with only stretch width takes up the remaining spaces after dividing it equally.

For tables with small data columns (e.g. counts), this results in data in longer fields being cut off.

Could we add a property that allows the use of `auto` for widths?

**Comment by PrzemyslawKlys** [comment]
Implemented in 2.3.0. Feel free to PR next time :)

**Comment by ObsidianPhoenix** [comment]
Cheers. 

Will do: typically I follow the MS process, and don't PR unless it's approved by the owners.

Great job on the module btw. Definitely seems to make it easier

**Comment by PrzemyslawKlys** [comment]
I am not MS, I need help :D If things can be more configurable - great. If things can be improved - even better.
