### ISSUE TITLE
Question more than issue

### ISSUE THREAD

**Issue by EMarcais** [EvotecIT/PSTeams#52]
Hi!
Thanks for the module this is perfect. 

I'm working on getting a text parsed correctly to be displayed as a paragraph with some newlines. 
Don't think it's an issue but i'm stuck on this one.

I tried: 
`$text.replace(". ",". \n\n") `
`New-AdaptiveTextBlock -Text "$text" -Wrap`
and the result in -returnJson is:
`BlabLaBla. \\n\\nBlablaBla`

But the only think that is displayed is the \n\n characters in the text visible in Teams.

Best!

**Comment by PrzemyslawKlys** [comment]
You should use "PowerShell" way for new lines.
```powershell
New-AdaptiveTextBlock -Text "Now that we have defined the main `n`n rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation." -Wrap
```
This will be converted to \n\n and it will work.

**Comment by EMarcais** [comment]
This is the best results: 
replace(". ",". \\`n")

**Comment by PrzemyslawKlys** [comment]
It has to be double n. Not just one.

**Comment by EMarcais** [comment]
To me this is the only it behave like it should. This is weird.

**Comment by PrzemyslawKlys** [comment]
As long as it works ;)
