### ISSUE TITLE
WARNING: Send-TeamsMessageBody - Couldn't send message. Execute message: Webhook message delivery failed with error: Microsoft Teams endpoint returned HTTP error 413

### ISSUE THREAD

**Issue by chaoscreater** [EvotecIT/PSTeams#53]
I'm getting the following error and it seems like the payload is too big. 

These are the links I found that seem to be related:
https://github.com/prometheus-msteams/prometheus-msteams/issues/29
https://stackoverflow.com/questions/49199443/microsoft-flow-sharepoint-to-teams-http-413

Does the module support chunking the message?

**Comment by PrzemyslawKlys** [comment]
No - we don't support chunking. There are couple reasons why:

1. I don't know exact value when it breaks - I guess your article says 28KB
2. For every single data I would need to check whether we are at the limit or not - time consuming
3. Once we are at the limit, lets say we are in the middle of 3rd row 2nd column - how would I react? I have no clue what you as a user wanted. 

Therefore I see this as something that is up to you to figure out messages small enough to fit your needs.
