### ISSUE TITLE
Table adaptive card column limit?

### ISSUE THREAD

**Issue by chaoscreater** [EvotecIT/PSTeams#54]
I'm able to output a table with 6 columns, but it seems like if I add more columns to the PSCustomObject, Teams doesn't generate the message. Is there a limit on how many columns you can output?

**Comment by PrzemyslawKlys** [comment]
Not a direct limit 

![image](https://github.com/EvotecIT/PSTeams/assets/15063294/1e791f52-d543-4996-ba5c-da17ceba39b8)

I guess whatever fits the screen - stays.
