### ISSUE TITLE
Verbose output for Send-TeamsMessage processed out of order

### ISSUE THREAD

**Issue by comnam90** [EvotecIT/PSTeams#6]
Currently the verbose output from Send-TeamsMessage returns blank values for `$Execute` and `$Body` because they're called before the variables are set.

Currently it looks like this:
https://github.com/EvotecIT/PSTeams/blob/01b3c7099169679fb3535a0c22735cd32e4b5f70/Public/Send-TeamsMessage.ps1#L22-L32

But should look like this:
```
 Write-Verbose "Send-TeamsMessage - Color: $Color ColorConverted: $ThemeColor" 
 Write-Verbose "Send-TeamsMessage - Color: $Color Color HEX $ThemeColor" 
 $Body = Add-TeamsBody -MessageTitle $MessageTitle ` 
     -MessageText $MessageText ` 
     -ThemeColor $ThemeColor ` 
     -Sections $Sections ` 
     -MessageSummary $MessageSummary 
$Execute = {Invoke-RestMethod -Uri $uri -Method Post -Body $Body -ContentType 'application/json'"}
Write-Verbose "Send-TeamsMessage - Execute $Execute Body $Body" 
 try { 
     & $Execute
} catch { 
```

**Comment by PrzemyslawKlys** [comment]
Right, I've moved this by accident it seems. Thanks for noticing.

**Comment by PrzemyslawKlys** [comment]
Released new version. I've not used your approach but simply moved Write-Verbose to the end.  I wanted to get proper value from $Execute in Write-Verbose.
