### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by hjorslev** [EvotecIT/PSTeams#8]
I am experiencing issues with using Danish characters such as æ ø å / Æ Ø Å when sending a message to MS Teams.

This could be resolved by adding `charset=utf-8` to -ContentType:

```powershell
$Execute = Invoke-RestMethod -Uri $uri -Method Post -Body $Body -ContentType 'application/json; charset=utf-8'
```

What do you think about adding an -Encoding parameter to allow different encodings?

**Comment by PrzemyslawKlys** [comment]
Ye, sure. Would you be able to come up with a full list so that it defaults to utf-8 but rest is added as ValidateSet? I never tested with Polish, I should have ;-)

**Comment by PrzemyslawKlys** [comment]
Your fix added Emoji :-) Thank you again!

**Comment by hjorslev** [comment]
Your welcome! Thanks for your quick response :-)
